MetaScript(0,17,0);
  write('console.log(');
write(JSON.stringify("included"));
  write(');\r\n');
  write('\r\n');
  write('// This will be indented once more:\r\n');
__='    ';
if (YEP) include("sub/someotherinclude.js");
  write('\r\n');
  write('// This should say \'undefined\' as NOPE is not visible in other files:\r\n');
  write('// ');
write(typeof NOPE);
writeln();
  write('\r\n');
  write('// This should say \'undefined\' as filename is not visible in __runProgram:\r\n');
  write('// ');
write(typeof filename === 'undefined' ? 'undefined' : filename);
writeln();
  write('\r\n');
